pimcore_data_hub:
    configurations:
        ElectronicImporter:
            general:
                active: true
                type: dataImporterDataObject
                name: ElectronicImporter
                description: ''
                group: DataImporter
                path: null
                modificationDate: 1676551766
                createDate: 1676229398
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/export (5).csv'
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ;
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: electronic
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: '/Product Data/Electronics/Mobiles/Sumsung/s10/s10ultra'
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
