pimcore:
    workflows:
        workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Laptop'
            places:
            
                new:
                    label: "New product"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: 4

                review_rejected:
                    label: "Rejected product"
                    title: "Product has been rejected"
                    color: "red"

                data_entry:
                    label: 'Data Entry'
                    title: 'Ready for Data Entry'
                    color: '#28a013'
                    permissions:
                        - objectLayout: 1

                data_entry_in_progress:
                    label: 'Data Entry: In Progress'
                    title: 'Data Entry role is working on enriching the data'
                    color: '#d9ef36'
                    permissions:
                    - objectLayout: 1

                data_entry_completed:
                    label: 'Data Entry: Completed'
                    title: 'Data Entry role has completed the data enrichment'
                    color: '#28a013'
                    permissions:
                        - objectLayout: 1

                ready_for_media:
                    label: 'Ready for Media'
                    title: 'Ready for Media Update'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 2

                media_update_inprogress:
                    label: 'Media Update In Progress'
                    title: 'Media Update is In Progress'
                    color: '#28a013'
                    permissions:
                            - objectLayout: 2

                media_update_done:
                    label: 'Media Update Done'
                    title: 'Media Update is Done'
                    color: '#009432'
                    permissions:
                           - objectLayout: 2                     

                review_needed:
                    label: 'Review Needed'
                    title: 'Object needs to be reviewed'
                    color: '#f7a831'
                    permissions:
                        - objectLayout: 3
                
                reviewer_in_progress:
                    label: 'Reviewer: In Progress'
                    title: 'Reviewer role is reviewing the object'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 3
                
                reviewer_approved:
                    label: 'Reviewer: Approved'
                    title: 'Reviewer role has approved the object'
                    color: '#28a013'
                    permissions:
                        - objectLayout: 3
                
                published:
                    label: 'Published'
                    title: 'Object is published and live'
                    color: '#28a013'

            transitions:

                reject_product:
                    from: [new,data_entry,data_entry_completed,ready_for_media,media_update_done,review_needed,reviewer_in_progress]
                    to: review_rejected
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Reject the product"
                        notes:
                            commentEnabled: true
                            commentRequired: true    

                start_processing_product:
                    from: new
                    to: data_entry
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Start Processing"

                start_data_entry_for_product:
                    from: data_entry
                    to: data_entry_in_progress
                    guard: "is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "Start Data Entry "

                data_entry_for_product_completed:
                    from: data_entry_in_progress
                    to: data_entry_completed
                    guard: "is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "Data Entry Done"
                
                ready_for_media:
                    from: data_entry_completed
                    to: ready_for_media
                    guard: "is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "Pass For Media Section Update"
                
                media_processing:
                    from: ready_for_media
                    to: media_update_inprogress
                    guard: "is_granted('ROLE_MEDIA')"
                    options:
                        label: "Start Media update"

                media_processing_completed:
                    from: media_update_inprogress
                    to: media_update_done
                    guard: "is_granted('ROLE_MEDIA')"
                    options:
                        label: "Media Update Done"
                
                send_for_review:
                    from: media_update_done
                    to: review_needed
                    guard: "is_granted('ROLE_MEDIA')"
                    options:
                        label: "Send For Review"

                review_started: 
                    from: review_needed
                    to: reviewer_in_progress
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Start Review"              
                
                reviewer_approved: 
                    from: reviewer_in_progress
                    to: reviewer_approved
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Product Approved"

                publish:
                    from: reviewer_approved
                    to: published
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Publish the product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            additionalFields:
                                - name: "timeWorked"
                                  fieldType: "input"
                                  title: "Time Spent"
                                  required: true
                
                send_back_to_media_entry:
                    from: reviewer_in_progress
                    to: ready_for_media
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Send Back for Media Update"

                send_back_to_data_entry:
                    from: reviewer_in_progress
                    to: data_entry
                    guard: "is_granted('ROLE_REVIEW')"
                    options:
                        label: "Send Back for Data Entry"
                