pimcore:
  workflows:
    workflow:
      label: "Product Workflow"
      type: "state_machine"
      supports:
        - 'Pimcore\Model\DataObject\Electronic'

      places:
        new:
          label: "New product"
          color: "#377ea9"
          permissions:
            - objectLayout: 1

        rejected:
          label: "Rejected product"
          color: "#28a013"

        content_prepared:
          label: "Content Prepared"
          title: "Content ready to publish"
          color: "#28a013"

        accepted:
          label: "Accepted product"
          color: "#28a013"

        media_content:
          label: "Update Media"
          title: "Updating Media"
          color: "#d9ef36"
          permissions:
            - objectLayout: 2

      transitions:
        reject_product:
          from: [new, content_prepared]
          to: rejected
          guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
          options:
            label: "Reject the product"
            notes:
              commentEnabled: false
              commentRequired: false

        start_processing:
          from: new
          to: media_content
          guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
          options:
            label: "updating media to the product"

        start_reviewing:
          from: media_content
          to: content_prepared
          guard: "is_fully_authenticated() and is_granted('ROLE_MEDIAROLE')"
          options:
            label: "updating media to the product"

        editing_needed:
          from: content_prepared
          to: new
          guard: "is_fully_authenticated() and is_granted('ROLE_REVIEWERROLE')"
          options:
            label: "EntryUser edit the data"

        publish:
          from: content_prepared
          to: accepted
          guard: "is_fully_authenticated() and is_granted('ROLE_REVIEWERROLE')"
          options:
            label: "Publish the product"
            notes:
              commentEnabled: false
              commentRequired: false
              additionalFields:
                - name: "timeWorked"
                  fieldType: "input"
                  title: "Time Spent"
                  required: true
