pimcore:
    custom_report:
        definitions:
            Electronic:
                name: Electronic
                sql: ''
                dataSourceConfig:
                    -
                        sql: 'brand,Count(*)'
                        from: object_electronic
                        where: ''
                        groupby: brand
                        type: sql
                columnConfiguration:
                    -
                        name: Brand
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel4666-1
                    -
                        name: 'Count(*)'
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel4666-2
                niceName: ''
                group: ''
                groupIconClass: ''
                iconClass: ''
                menuShortcut: true
                reportClass: ''
                chartType: pie
                pieColumn: null
                pieLabelColumn: null
                xAxis: null
                yAxis: {  }
                modificationDate: 1676271364
                creationDate: 1676269285
                shareGlobally: true
                sharedUserNames: {  }
                sharedRoleNames: {  }
